name: cargo fmt

runs:
  using: composite
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
          components: rustfmt, clippy
      - name: Cargo fmt
        run: cargo fmt -- --check